apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stacks.wse.com
spec:
  group: wse.com
  names:
    kind: Stack
    listKind: StackList
    plural: stacks
  scope: Namespaced
  version: v1
